### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_fpga_all#3]
Is there a schedule for the next *psi_fpga_all* release? 

I think there were quite some changes (which also changed dependencies of some repos) and new repos were added (at least the axi_parameter_ram vivado IP core). So it would be great having a new psi_fpga_all release that contains a snapshot of versions that are proven to work together.

**Comment by obruendl** [comment]
@BenoitStef 
Is there any update on this?

**Comment by BenoitStef** [comment]
it's on going

**Comment by BenoitStef** [comment]
Done
