### ISSUE TITLE
copy/paste error on sync FIFO documentation

### ISSUE THREAD

**Issue by 0xF5A1** [paulscherrerinstitute/psi_fpga_all#5]
Sync FIFO interface documentation seems to be copied from async FIFO and has non-existing interfaces (In/Out AlmFull, etc):
https://github.com/paulscherrerinstitute/psi_common/blob/7074a5d29ee368eb5858df78f785d8dd4665ea3c/doc/ch4_fifos/ch4_2_sync_fifo.md

**Comment by BenoitStef** [comment]
Hi 0xF5A1,
It's correct thx for the "errata" findings, I modified it and will be added to new release of **psi_common** soon
greetings

**Comment by BenoitStef** [comment]
For info you have the new release at following link if required [https://github.com/paulscherrerinstitute/psi_common/blob/master/doc/ch4_fifos/ch4_2_sync_fifo.md](url).
You can update the submodule

**Comment by BenoitStef** [comment]
[https://github.com/paulscherrerinstitute/psi_common/blob/master/doc/ch4_fifos/ch4_2_sync_fifo.md](https://github.com/paulscherrerinstitute/psi_common/blob/master/doc/ch4_fifos/ch4_2_sync_fifo.md)
